name: Feature request
description: Propose an improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
  - type: textarea
    attributes:
      label: Additional context
